#!/usr/bin/env php
<?php

exit(main());

function main():int {
    $messages = [];
    output('find_template', 'parse_template', $messages);
    output('find_call', 'parse_call', $messages);

    return 0;
}

function find_template(): array {
    exec(
        "find resources -type f -name '*.html' -print0 | xargs -0 grep -EHn 't(md|f)? \\$?.Locale \"'",
        $calls,
    );

    return $calls;
}

function output(callable $finder, callable $parser, array &$messages) {
    foreach ($finder() as $v) {
        list($path, $line, $raw) = explode(':', $v, 3);
        $id = $parser($raw);
        if ($id === null) {
            fprintf(STDERR, "Unable to parse $path:$line: $v\n");
            continue;
        }

        if (array_key_exists($id, $messages)) {
            continue;
        }
        $messages[$id] = true;

        echo "#: $path:$line\n";
        echo "msgid $id\n";
        echo "msgstr \"\"\n\n";
    }

    return 0;
}

function parse_template(string $str): ?string {
    preg_match('`\{\{\s*t(md|f)?\s+\$?\.Locale\s+"([^"]*)".*\}\}`', $str, $matches);
    if (count($matches) < 3) {
        return null;
    }

    return json_encode($matches[2]);
}

function find_call(): array {
    exec("find internal -type f -name '*.go' -print0 | " .
        "xargs -0 grep -EHn 's\.locales\[locale\]\.Get\(\"(.+)\"\)'",
        $calls,
    );

    return $calls;
}

function parse_call(string $str): ?string {
    preg_match('`s\.locales\[locale\]\.Get\("(.+)"\)`', $str, $matches);
    if (count($matches) < 2) {
        return null;
    }

    return json_encode($matches[1]);
}
