
INSERT INTO Location ("Name", "RegionID", "HintType") VALUES
    ('Kokiri Sword Chest', 1, 0),
    ('Mido Chest Top Left', 1, 0),
    ('Mido Chest Top Right', 1, 0),
    ('Mido Chest Bottom Left', 1, 0),
    ('Mido Chest Bottom Right', 1, 0),
    ('Shield Grave Chest', 2, 0),
    ('Heart Piece Grave Chest', 2, 1),
    ('Composer Grave Chest', 2, 1),
    ('Death Mountain Bombable Chest', 3, 0),
    ('Goron City Leftmost Maze Chest', 4, 1),
    ('Goron City Right Maze Chest', 4, 0),
    ('Goron City Left Maze Chest', 4, 0),
    ('Zoras Domain Torch Run', 5, 0),
    ('Hookshot Chest', 2, 0),
    ('Gerudo Valley Hammer Rocks Chest', 6, 1),
    ('Gerudo Fortress Rooftop Chest', 7, 0),
    ('Haunted Wasteland Structure Chest', 8, 1),
    ('Redead Grotto Chest', 9, 0),
    ('Wolfos Grotto Chest', 10, 0),
    ('Field West Castle Town Grotto Chest', 11, 0),
    ('Remote Southern Grotto Chest', 11, 0),
    ('Field Near Lake Outside Fence Grotto Chest', 11, 0),
    ('Kakariko Back Grotto Chest', 9, 0),
    ('Zora River Plateau Open Grotto Chest', 12, 0),
    ('Kokiri Forest Storms Grotto Chest', 1, 0),
    ('Lost Woods Generic Grotto Chest', 13, 0),
    ('Mountain Storms Grotto Chest', 3, 0),
    ('Top of Crater Grotto Chest', 14, 0),
    ('Treasure Chest Game', 15, 1),
    ('Zelda', 16, 0),
    ('Gift from Saria', 13, 0),
    ('Zoras Fountain Fairy Reward', 17, 0),
    ('Hyrule Castle Fairy Reward', 18, 0),
    ('Desert Colossus Fairy Reward', 19, 0),
    ('Mountain Summit Fairy Reward', 3, 0),
    ('Crater Fairy Reward', 14, 0),
    ('Ganons Castle Fairy Reward', 20, 0),
    ('Sheik Forest Song', 10, 1),
    ('Sheik in Crater', 14, 1),
    ('Sheik in Ice Cavern', 21, 1),
    ('Sheik at Colossus', 19, 1),
    ('Sheik in Kakariko', 9, 2),
    ('Sheik at Temple', 16, 1),
    ('Impa at Castle', 18, 0),
    ('Song from Malon', 22, 0),
    ('Song from Saria', 10, 0),
    ('Song from Composer Grave', 2, 1),
    ('Song from Ocarina of Time', 11, 2),
    ('Song at Windmill', 9, 0),
    ('Malon Egg', 18, 0),
    ('Zeldas Letter', 18, 0),
    ('Darunias Joy', 4, 1),
    ('Diving Minigame', 5, 0),
    ('Child Fishing', 23, 0),
    ('Adult Fishing', 23, 0),
    ('Diving in the Lab', 23, 0),
    ('Link the Goron', 4, 0),
    ('King Zora Thawed', 5, 1),
    ('Bombchu Bowling Bomb Bag', 15, 0),
    ('Bombchu Bowling Piece of Heart', 15, 0),
    ('Bombchu Bowling Bombchus', 15, 0),
    ('Dog Lady', 15, 0),
    ('Skull Kid', 13, 1),
    ('Ocarina Memory Game', 13, 0),
    ('10 Gold Skulltula Reward', 9, 0),
    ('20 Gold Skulltula Reward', 9, 1),
    ('30 Gold Skulltula Reward', 9, 2),
    ('40 Gold Skulltula Reward', 9, 2),
    ('50 Gold Skulltula Reward', 9, 2),
    ('Man on Roof', 9, 0),
    ('Magic Bean Salesman', 12, 0),
    ('Frog Ocarina Game', 12, 0),
    ('Frogs in the Rain', 12, 0),
    ('Horseback Archery 1000 Points', 7, 0),
    ('Horseback Archery 1500 Points', 7, 1),
    ('Child Shooting Gallery', 15, 0),
    ('Adult Shooting Gallery', 9, 1),
    ('Target in Woods', 13, 0),
    ('Deku Theater Skull Mask', 13, 2),
    ('Deku Theater Mask of Truth', 13, 0),
    ('Anju as Adult', 9, 0),
    ('Biggoron', 3, 2),
    ('Anjus Chickens', 9, 1),
    ('Talons Chickens', 22, 0),
    ('10 Big Poes', 15, 2),
    ('Rolling Goron as Child', 4, 0),
    ('Underwater Bottle', 23, 0),
    ('Lake Hylia Sun', 23, 1),
    ('Gerudo Fortress Membership Card', 7, 0),
    ('Ocarina of Time', 11, 1),
    ('Haunted Wasteland Bombchu Salesman', 8, 0),
    ('Impa House Freestanding PoH', 9, 0),
    ('Tektite Grotto Freestanding PoH', 11, 0),
    ('Windmill Freestanding PoH', 9, 0),
    ('Dampe Race Freestanding PoH', 2, 0),
    ('Lon Lon Tower Freestanding PoH', 22, 0),
    ('Graveyard Freestanding PoH', 2, 0),
    ('Gravedigging Tour', 2, 0),
    ('Zora River Lower Freestanding PoH', 12, 0),
    ('Zora River Upper Freestanding PoH', 12, 0),
    ('Lake Hylia Freestanding PoH', 23, 0),
    ('Zoras Fountain Iceberg Freestanding PoH', 17, 0),
    ('Zoras Fountain Bottom Freestanding PoH', 17, 1),
    ('Gerudo Valley Waterfall Freestanding PoH', 6, 0),
    ('Gerudo Valley Crate Freestanding PoH', 6, 0),
    ('Colossus Freestanding PoH', 19, 0),
    ('DM Trail Freestanding PoH', 3, 0),
    ('DM Crater Wall Freestanding PoH', 14, 0),
    ('DM Crater Volcano Freestanding PoH', 14, 0),
    ('Goron City Pot Freestanding PoH', 4, 1),
    ('Gerudo Fortress North F1 Carpenter', 7, 0),
    ('Gerudo Fortress North F2 Carpenter', 7, 0),
    ('Gerudo Fortress South F1 Carpenter', 7, 0),
    ('Gerudo Fortress South F2 Carpenter', 7, 0),
    ('Deku Tree Lobby Chest', 24, 0),
    ('Deku Tree Slingshot Chest', 24, 0),
    ('Deku Tree Slingshot Room Side Chest', 24, 0),
    ('Deku Tree Compass Chest', 24, 0),
    ('Deku Tree Compass Room Side Chest', 24, 0),
    ('Deku Tree Basement Chest', 24, 0),
    ('Deku Tree MQ Lobby Chest', 24, 0),
    ('Deku Tree MQ Compass Chest', 24, 0),
    ('Deku Tree MQ Slingshot Chest', 24, 0),
    ('Deku Tree MQ Slingshot Room Back Chest', 24, 0),
    ('Deku Tree MQ Basement Chest', 24, 0),
    ('Deku Tree MQ Before Spinning Log Chest', 24, 0),
    ('Deku Tree MQ After Spinning Log Chest', 24, 1),
    ('Chest Above King Dodongo', 25, 0),
    ('Dodongos Cavern Map Chest', 25, 0),
    ('Dodongos Cavern Compass Chest', 25, 0),
    ('Dodongos Cavern Bomb Flower Platform', 25, 0),
    ('Dodongos Cavern Bomb Bag Chest', 25, 0),
    ('Dodongos Cavern End of Bridge Chest', 25, 0),
    ('Dodongos Cavern MQ Map Chest', 25, 0),
    ('Dodongos Cavern MQ Bomb Bag Chest', 25, 0),
    ('Dodongos Cavern MQ Compass Chest', 25, 0),
    ('Dodongos Cavern MQ Larva Room Chest', 25, 0),
    ('Dodongos Cavern MQ Torch Puzzle Room Chest', 25, 0),
    ('Dodongos Cavern MQ Under Grave Chest', 25, 0),
    ('Boomerang Chest', 26, 1),
    ('Jabu Jabus Belly Map Chest', 26, 0),
    ('Jabu Jabus Belly Compass Chest', 26, 0),
    ('Jabu Jabus Belly MQ Entry Side Chest', 26, 0),
    ('Jabu Jabus Belly MQ Map Chest', 26, 0),
    ('Jabu Jabus Belly MQ Second Room Lower Chest', 26, 0),
    ('Jabu Jabus Belly MQ Compass Chest', 26, 0),
    ('Jabu Jabus Belly MQ Second Room Upper Chest', 26, 0),
    ('Jabu Jabus Belly MQ Basement North Chest', 26, 0),
    ('Jabu Jabus Belly MQ Basement South Chest', 26, 0),
    ('Jabu Jabus Belly MQ Near Boss Chest', 26, 0),
    ('Jabu Jabus Belly MQ Falling Like Like Room Chest', 26, 0),
    ('Jabu Jabus Belly MQ Boomerang Room Small Chest', 26, 0),
    ('MQ Boomerang Chest', 26, 0),
    ('Jabu Jabus Belly MQ Cow', 26, 0),
    ('Forest Temple First Chest', 27, 0),
    ('Forest Temple Chest Behind Lobby', 27, 0),
    ('Forest Temple Well Chest', 27, 0),
    ('Forest Temple Map Chest', 27, 0),
    ('Forest Temple Outside Hookshot Chest', 27, 0),
    ('Forest Temple Falling Room Chest', 27, 0),
    ('Forest Temple Block Push Chest', 27, 0),
    ('Forest Temple Boss Key Chest', 27, 0),
    ('Forest Temple Floormaster Chest', 27, 1),
    ('Forest Temple Bow Chest', 27, 0),
    ('Forest Temple Red Poe Chest', 27, 0),
    ('Forest Temple Blue Poe Chest', 27, 0),
    ('Forest Temple Near Boss Chest', 27, 0),
    ('Forest Temple MQ First Chest', 27, 0),
    ('Forest Temple MQ Chest Behind Lobby', 27, 0),
    ('Forest Temple MQ Bow Chest', 27, 0),
    ('Forest Temple MQ NE Outdoors Lower Chest', 27, 0),
    ('Forest Temple MQ NE Outdoors Upper Chest', 27, 0),
    ('Forest Temple MQ Well Chest', 27, 0),
    ('Forest Temple MQ Map Chest', 27, 0),
    ('Forest Temple MQ Compass Chest', 27, 0),
    ('Forest Temple MQ Falling Room Chest', 27, 0),
    ('Forest Temple MQ Near Boss Chest', 27, 0),
    ('Forest Temple MQ Redead Chest', 27, 0),
    ('Forest Temple MQ Boss Key Chest', 27, 0),
    ('Fire Temple Chest Near Boss', 28, 0),
    ('Fire Temple Fire Dancer Chest', 28, 0),
    ('Fire Temple Boss Key Chest', 28, 0),
    ('Fire Temple Big Lava Room Bombable Chest', 28, 0),
    ('Fire Temple Big Lava Room Open Chest', 28, 0),
    ('Fire Temple Boulder Maze Lower Chest', 28, 0),
    ('Fire Temple Boulder Maze Upper Chest', 28, 0),
    ('Fire Temple Boulder Maze Side Room', 28, 0),
    ('Fire Temple Boulder Maze Bombable Pit', 28, 0),
    ('Fire Temple Scarecrow Chest', 28, 1),
    ('Fire Temple Map Chest', 28, 0),
    ('Fire Temple Compass Chest', 28, 0),
    ('Fire Temple Highest Goron Chest', 28, 0),
    ('Fire Temple Megaton Hammer Chest', 28, 1),
    ('Fire Temple MQ Chest Near Boss', 28, 0),
    ('Fire Temple MQ Megaton Hammer Chest', 28, 0),
    ('Fire Temple MQ Compass Chest', 28, 0),
    ('Fire Temple MQ Maze Lower Chest', 28, 0),
    ('Fire Temple MQ Maze Upper Chest', 28, 0),
    ('Fire Temple MQ West Tower Top Chest', 28, 1),
    ('Fire Temple MQ Entrance Hallway Small Chest', 28, 0),
    ('Fire Temple MQ Map Chest', 28, 0),
    ('Fire Temple MQ Boss Key Chest', 28, 0),
    ('Fire Temple MQ Big Lava Room Bombable Chest', 28, 0),
    ('Fire Temple MQ Maze Side Room', 28, 0),
    ('Fire Temple MQ Freestanding Key', 28, 0),
    ('Water Temple Map Chest', 29, 0),
    ('Water Temple Compass Chest', 29, 0),
    ('Water Temple Torches Chest', 29, 0),
    ('Water Temple Dragon Chest', 29, 0),
    ('Water Temple Central Bow Target Chest', 29, 0),
    ('Water Temple Central Pillar Chest', 29, 0),
    ('Water Temple Cracked Wall Chest', 29, 0),
    ('Water Temple Boss Key Chest', 29, 1),
    ('Water Temple Dark Link Chest', 29, 0),
    ('Water Temple River Chest', 29, 1),
    ('Water Temple MQ Central Pillar Chest', 29, 0),
    ('Water Temple MQ Boss Key Chest', 29, 1),
    ('Water Temple MQ Longshot Chest', 29, 0),
    ('Water Temple MQ Compass Chest', 29, 0),
    ('Water Temple MQ Map Chest', 29, 0),
    ('Water Temple MQ Freestanding Key', 29, 1),
    ('Silver Gauntlets Chest', 30, 1),
    ('Mirror Shield Chest', 30, 1),
    ('Spirit Temple Child Left Chest', 30, 0),
    ('Spirit Temple Child Right Chest', 30, 0),
    ('Spirit Temple Compass Chest', 30, 0),
    ('Spirit Temple Early Adult Right Chest', 30, 0),
    ('Spirit Temple First Mirror Right Chest', 30, 0),
    ('Spirit Temple First Mirror Left Chest', 30, 0),
    ('Spirit Temple Map Chest', 30, 0),
    ('Spirit Temple Child Climb East Chest', 30, 0),
    ('Spirit Temple Child Climb North Chest', 30, 0),
    ('Spirit Temple Sun Block Room Chest', 30, 0),
    ('Spirit Temple Statue Hand Chest', 30, 0),
    ('Spirit Temple NE Main Room Chest', 30, 0),
    ('Spirit Temple Near Four Armos Chest', 30, 0),
    ('Spirit Temple Hallway Left Invisible Chest', 30, 0),
    ('Spirit Temple Hallway Right Invisible Chest', 30, 0),
    ('Spirit Temple Boss Key Chest', 30, 0),
    ('Spirit Temple Topmost Chest', 30, 0),
    ('Spirit Temple MQ Entrance Front Left Chest', 30, 0),
    ('Spirit Temple MQ Entrance Back Right Chest', 30, 0),
    ('Spirit Temple MQ Entrance Front Right Chest', 30, 0),
    ('Spirit Temple MQ Entrance Back Left Chest', 30, 0),
    ('Spirit Temple MQ Child Center Chest', 30, 1),
    ('Spirit Temple MQ Map Chest', 30, 0),
    ('Spirit Temple MQ Child Left Chest', 30, 0),
    ('Spirit Temple MQ Child Climb North Chest', 30, 0),
    ('Spirit Temple MQ Child Climb South Chest', 30, 0),
    ('Spirit Temple MQ Compass Chest', 30, 0),
    ('Spirit Temple MQ Lower NE Main Room Chest', 30, 0),
    ('Spirit Temple MQ Upper NE Main Room Chest', 30, 0),
    ('Spirit Temple MQ Silver Block Hallway Chest', 30, 0),
    ('Spirit Temple MQ Sun Block Room Chest', 30, 0),
    ('Spirit Temple MQ Lower Adult Right Chest', 30, 1),
    ('Spirit Temple MQ Lower Adult Left Chest', 30, 0),
    ('Spirit Temple MQ Beamos Room Chest', 30, 0),
    ('Spirit Temple MQ Ice Trap Chest', 30, 0),
    ('Spirit Temple MQ Boss Key Chest', 30, 0),
    ('Spirit Temple MQ Mirror Puzzle Invisible Chest', 30, 0),
    ('Shadow Temple Map Chest', 31, 0),
    ('Shadow Temple Hover Boots Chest', 31, 0),
    ('Shadow Temple Compass Chest', 31, 0),
    ('Shadow Temple Early Silver Rupee Chest', 31, 0),
    ('Shadow Temple Invisible Blades Visible Chest', 31, 0),
    ('Shadow Temple Invisible Blades Invisible Chest', 31, 0),
    ('Shadow Temple Falling Spikes Lower Chest', 31, 0),
    ('Shadow Temple Falling Spikes Upper Chest', 31, 0),
    ('Shadow Temple Falling Spikes Switch Chest', 31, 0),
    ('Shadow Temple Invisible Spikes Chest', 31, 0),
    ('Shadow Temple Wind Hint Chest', 31, 0),
    ('Shadow Temple After Wind Enemy Chest', 31, 0),
    ('Shadow Temple After Wind Hidden Chest', 31, 0),
    ('Shadow Temple Spike Walls Left Chest', 31, 0),
    ('Shadow Temple Boss Key Chest', 31, 0),
    ('Shadow Temple Hidden Floormaster Chest', 31, 1),
    ('Shadow Temple Freestanding Key', 31, 0),
    ('Shadow Temple MQ Compass Chest', 31, 0),
    ('Shadow Temple MQ Hover Boots Chest', 31, 0),
    ('Shadow Temple MQ Early Gibdos Chest', 31, 0),
    ('Shadow Temple MQ Map Chest', 31, 0),
    ('Shadow Temple MQ Beamos Silver Rupees Chest', 31, 0),
    ('Shadow Temple MQ Falling Spikes Switch Chest', 31, 0),
    ('Shadow Temple MQ Falling Spikes Lower Chest', 31, 0),
    ('Shadow Temple MQ Falling Spikes Upper Chest', 31, 0),
    ('Shadow Temple MQ Invisible Spikes Chest', 31, 0),
    ('Shadow Temple MQ Boss Key Chest', 31, 0),
    ('Shadow Temple MQ Spike Walls Left Chest', 31, 0),
    ('Shadow Temple MQ Stalfos Room Chest', 31, 0),
    ('Shadow Temple MQ Invisible Blades Invisible Chest', 31, 0),
    ('Shadow Temple MQ Invisible Blades Visible Chest', 31, 0),
    ('Shadow Temple MQ Bomb Flower Chest', 31, 1),
    ('Shadow Temple MQ Wind Hint Chest', 31, 0),
    ('Shadow Temple MQ After Wind Hidden Chest', 31, 0),
    ('Shadow Temple MQ After Wind Enemy Chest', 31, 0),
    ('Shadow Temple MQ Near Ship Invisible Chest', 31, 0),
    ('Shadow Temple MQ Freestanding Key', 31, 0),
    ('Bottom of the Well Front Left Hidden Wall', 32, 0),
    ('Bottom of the Well Front Center Bombable', 32, 0),
    ('Bottom of the Well Right Bottom Hidden Wall', 32, 0),
    ('Bottom of the Well Center Large Chest', 32, 0),
    ('Bottom of the Well Center Small Chest', 32, 0),
    ('Bottom of the Well Back Left Bombable', 32, 0),
    ('Bottom of the Well Defeat Boss', 32, 1),
    ('Bottom of the Well Invisible Chest', 32, 0),
    ('Bottom of the Well Underwater Front Chest', 32, 0),
    ('Bottom of the Well Underwater Left Chest', 32, 0),
    ('Bottom of the Well Basement Chest', 32, 0),
    ('Bottom of the Well Locked Pits', 32, 0),
    ('Bottom of the Well Behind Right Grate', 32, 0),
    ('Bottom of the Well Freestanding Key', 32, 0),
    ('Bottom of the Well MQ Map Chest', 32, 0),
    ('Bottom of the Well MQ Lens Chest', 32, 0),
    ('Bottom of the Well MQ Compass Chest', 32, 1),
    ('Bottom of the Well MQ Dead Hand Freestanding Key', 32, 0),
    ('Bottom of the Well MQ East Inner Room Freestanding Key', 32, 0),
    ('Ice Cavern Map Chest', 21, 0),
    ('Ice Cavern Compass Chest', 21, 0),
    ('Ice Cavern Iron Boots Chest', 21, 0),
    ('Ice Cavern Freestanding PoH', 21, 0),
    ('Ice Cavern MQ Iron Boots Chest', 21, 0),
    ('Ice Cavern MQ Compass Chest', 21, 0),
    ('Ice Cavern MQ Map Chest', 21, 0),
    ('Ice Cavern MQ Freestanding PoH', 21, 0),
    ('Gerudo Training Grounds Lobby Left Chest', 33, 0),
    ('Gerudo Training Grounds Lobby Right Chest', 33, 0),
    ('Gerudo Training Grounds Stalfos Chest', 33, 0),
    ('Gerudo Training Grounds Beamos Chest', 33, 0),
    ('Gerudo Training Grounds Hidden Ceiling Chest', 33, 0),
    ('Gerudo Training Grounds Maze Path First Chest', 33, 0),
    ('Gerudo Training Grounds Maze Path Second Chest', 33, 0),
    ('Gerudo Training Grounds Maze Path Third Chest', 33, 0),
    ('Gerudo Training Grounds Maze Path Final Chest', 33, 1),
    ('Gerudo Training Grounds Maze Right Central Chest', 33, 0),
    ('Gerudo Training Grounds Maze Right Side Chest', 33, 0),
    ('Gerudo Training Grounds Underwater Silver Rupee Chest', 33, 1),
    ('Gerudo Training Grounds Hammer Room Clear Chest', 33, 0),
    ('Gerudo Training Grounds Hammer Room Switch Chest', 33, 0),
    ('Gerudo Training Grounds Eye Statue Chest', 33, 0),
    ('Gerudo Training Grounds Near Scarecrow Chest', 33, 0),
    ('Gerudo Training Grounds Before Heavy Block Chest', 33, 0),
    ('Gerudo Training Grounds Heavy Block First Chest', 33, 0),
    ('Gerudo Training Grounds Heavy Block Second Chest', 33, 0),
    ('Gerudo Training Grounds Heavy Block Third Chest', 33, 0),
    ('Gerudo Training Grounds Heavy Block Fourth Chest', 33, 0),
    ('Gerudo Training Grounds Freestanding Key', 33, 0),
    ('Gerudo Training Grounds MQ Lobby Right Chest', 33, 0),
    ('Gerudo Training Grounds MQ Lobby Left Chest', 33, 0),
    ('Gerudo Training Grounds MQ First Iron Knuckle Chest', 33, 0),
    ('Gerudo Training Grounds MQ Before Heavy Block Chest', 33, 0),
    ('Gerudo Training Grounds MQ Eye Statue Chest', 33, 0),
    ('Gerudo Training Grounds MQ Flame Circle Chest', 33, 0),
    ('Gerudo Training Grounds MQ Second Iron Knuckle Chest', 33, 0),
    ('Gerudo Training Grounds MQ Dinolfos Chest', 33, 0),
    ('Gerudo Training Grounds MQ Ice Arrows Chest', 33, 1),
    ('Gerudo Training Grounds MQ Maze Right Central Chest', 33, 0),
    ('Gerudo Training Grounds MQ Maze Path First Chest', 33, 0),
    ('Gerudo Training Grounds MQ Maze Right Side Chest', 33, 0),
    ('Gerudo Training Grounds MQ Maze Path Third Chest', 33, 0),
    ('Gerudo Training Grounds MQ Maze Path Second Chest', 33, 0),
    ('Gerudo Training Grounds MQ Hidden Ceiling Chest', 33, 0),
    ('Gerudo Training Grounds MQ Underwater Silver Rupee Chest', 33, 1),
    ('Gerudo Training Grounds MQ Heavy Block Chest', 33, 0),
    ('Ganons Tower Boss Key Chest', 34, 0),
    ('Ganons Castle Forest Trial Chest', 34, 0),
    ('Ganons Castle Water Trial Left Chest', 34, 0),
    ('Ganons Castle Water Trial Right Chest', 34, 0),
    ('Ganons Castle Shadow Trial First Chest', 34, 0),
    ('Ganons Castle Shadow Trial Second Chest', 34, 0),
    ('Ganons Castle Spirit Trial First Chest', 34, 0),
    ('Ganons Castle Spirit Trial Second Chest', 34, 0),
    ('Ganons Castle Light Trial First Left Chest', 34, 0),
    ('Ganons Castle Light Trial Second Left Chest', 34, 0),
    ('Ganons Castle Light Trial Third Left Chest', 34, 0),
    ('Ganons Castle Light Trial First Right Chest', 34, 0),
    ('Ganons Castle Light Trial Second Right Chest', 34, 0),
    ('Ganons Castle Light Trial Third Right Chest', 34, 0),
    ('Ganons Castle Light Trial Invisible Enemies Chest', 34, 0),
    ('Ganons Castle Light Trial Lullaby Chest', 34, 0),
    ('Ganons Castle MQ Water Trial Chest', 34, 0),
    ('Ganons Castle MQ Forest Trial First Chest', 34, 0),
    ('Ganons Castle MQ Forest Trial Second Chest', 34, 0),
    ('Ganons Castle MQ Light Trial Lullaby Chest', 34, 0),
    ('Ganons Castle MQ Shadow Trial First Chest', 34, 0),
    ('Ganons Castle MQ Shadow Trial Second Chest', 34, 0),
    ('Ganons Castle MQ Spirit Trial Golden Gauntlets Chest', 34, 0),
    ('Ganons Castle MQ Spirit Trial Sun Back Right Chest', 34, 0),
    ('Ganons Castle MQ Spirit Trial Sun Back Left Chest', 34, 0),
    ('Ganons Castle MQ Spirit Trial Sun Front Left Chest', 34, 0),
    ('Ganons Castle MQ Spirit Trial First Chest', 34, 0),
    ('Ganons Castle MQ Spirit Trial Second Chest', 34, 0),
    ('Ganons Castle MQ Forest Trial Freestanding Key', 34, 0),
    ('Queen Gohma Heart', 24, 0),
    ('King Dodongo Heart', 25, 0),
    ('Barinade Heart', 26, 0),
    ('Phantom Ganon Heart', 27, 0),
    ('Volvagia Heart', 28, 0),
    ('Morpha Heart', 29, 0),
    ('Twinrova Heart', 30, 0),
    ('Bongo Bongo Heart', 31, 0),
    ('GS Deku Tree Basement Back Room', 24, 0),
    ('GS Deku Tree Basement Gate', 24, 0),
    ('GS Deku Tree Basement Vines', 24, 0),
    ('GS Deku Tree Compass Room', 24, 0),
    ('GS Deku Tree MQ Lobby', 24, 0),
    ('GS Deku Tree MQ Compass Room', 24, 0),
    ('GS Deku Tree MQ Basement Ceiling', 24, 1),
    ('GS Deku Tree MQ Basement Back Room', 24, 0),
    ('GS Dodongo's Cavern Vines Above Stairs', 25, 0),
    ('GS Dodongo's Cavern Scarecrow', 25, 0),
    ('GS Dodongo's Cavern Alcove Above Stairs', 25, 0),
    ('GS Dodongo's Cavern Back Room', 25, 0),
    ('GS Dodongo's Cavern East Side Room', 25, 0),
    ('GS Dodongo's Cavern MQ Scrub Room', 25, 0),
    ('GS Dodongo's Cavern MQ Song of Time Block Room', 25, 0),
    ('GS Dodongo's Cavern MQ Lizalfos Room', 25, 0),
    ('GS Dodongo's Cavern MQ Larva Room', 25, 0),
    ('GS Dodongo's Cavern MQ Back Area', 25, 0),
    ('GS Jabu Jabu Lobby Basement Lower', 26, 0),
    ('GS Jabu Jabu Lobby Basement Upper', 26, 0),
    ('GS Jabu Jabu Near Boss', 26, 0),
    ('GS Jabu Jabu Water Switch Room', 26, 0),
    ('GS Jabu Jabu MQ Tailpasaran Room', 26, 0),
    ('GS Jabu Jabu MQ Invisible Enemies Room', 26, 1),
    ('GS Jabu Jabu MQ Boomerang Room', 26, 0),
    ('GS Jabu Jabu MQ Near Boss', 26, 0),
    ('GS Forest Temple Outdoor East', 27, 0),
    ('GS Forest Temple First Room', 27, 0),
    ('GS Forest Temple Outdoor West', 27, 0),
    ('GS Forest Temple Lobby', 27, 0),
    ('GS Forest Temple Basement', 27, 0),
    ('GS Forest Temple MQ First Hallway', 27, 0),
    ('GS Forest Temple MQ Block Push Room', 27, 0),
    ('GS Forest Temple MQ Outdoor East', 27, 0),
    ('GS Forest Temple MQ Outdoor West', 27, 0),
    ('GS Forest Temple MQ Well', 27, 0),
    ('GS Fire Temple Song of Time Room', 28, 0),
    ('GS Fire Temple Basement', 28, 0),
    ('GS Fire Temple Unmarked Bomb Wall', 28, 0),
    ('GS Fire Temple East Tower Top', 28, 0),
    ('GS Fire Temple East Tower Climb', 28, 0),
    ('GS Fire Temple MQ Above Fire Wall Maze', 28, 1),
    ('GS Fire Temple MQ Fire Wall Maze Center', 28, 0),
    ('GS Fire Temple MQ Big Lava Room', 28, 0),
    ('GS Fire Temple MQ Fire Wall Maze Side Room', 28, 0),
    ('GS Fire Temple MQ East Tower Top', 28, 0),
    ('GS Water Temple South Basement', 29, 0),
    ('GS Water Temple Falling Platform Room', 29, 0),
    ('GS Water Temple Central Room', 29, 0),
    ('GS Water Temple Near Boss Key Chest', 29, 0),
    ('GS Water Temple Serpent River', 29, 0),
    ('GS Water Temple MQ Before Upper Water Switch', 29, 0),
    ('GS Water Temple MQ North Basement', 29, 1),
    ('GS Water Temple MQ Lizalfos Hallway', 29, 0),
    ('GS Water Temple MQ Serpent River', 29, 0),
    ('GS Water Temple MQ South Basement', 29, 0),
    ('GS Spirit Temple Hall to West Iron Knuckle', 30, 0),
    ('GS Spirit Temple Boulder Room', 30, 0),
    ('GS Spirit Temple Lobby', 30, 0),
    ('GS Spirit Temple Bomb for Light Room', 30, 0),
    ('GS Spirit Temple Metal Fence', 30, 0),
    ('GS Spirit Temple MQ Lower Adult Right', 30, 1),
    ('GS Spirit Temple MQ Lower Adult Left', 30, 0),
    ('GS Spirit Temple MQ Iron Knuckle West', 30, 0),
    ('GS Spirit Temple MQ Iron Knuckle North', 30, 0),
    ('GS Spirit Temple MQ Sun Block Room', 30, 0),
    ('GS Shadow Temple Single Giant Pot', 31, 0),
    ('GS Shadow Temple Crusher Room', 31, 0),
    ('GS Shadow Temple Triple Giant Pot', 31, 0),
    ('GS Shadow Temple Like Like Room', 31, 0),
    ('GS Shadow Temple Near Ship', 31, 0),
    ('GS Shadow Temple MQ Crusher Room', 31, 0),
    ('GS Shadow Temple MQ Wind Hint Room', 31, 0),
    ('GS Shadow Temple MQ After Wind', 31, 0),
    ('GS Shadow Temple MQ After Ship', 31, 0),
    ('GS Shadow Temple MQ Near Boss', 31, 0),
    ('GS Well Like Like Cage', 32, 0),
    ('GS Well East Inner Room', 32, 0),
    ('GS Well West Inner Room', 32, 0),
    ('GS Well MQ Basement', 32, 0),
    ('GS Well MQ Coffin Room', 32, 0),
    ('GS Well MQ West Inner Room', 32, 0),
    ('GS Ice Cavern Push Block Room', 21, 0),
    ('GS Ice Cavern Spinning Scythe Room', 21, 0),
    ('GS Ice Cavern Heart Piece Room', 21, 0),
    ('GS Ice Cavern MQ Scarecrow', 21, 0),
    ('GS Ice Cavern MQ Ice Block', 21, 0),
    ('GS Ice Cavern MQ Red Ice', 21, 0),
    ('GS Hyrule Field Near Gerudo Valley', 11, 1),
    ('GS Hyrule Field near Kakariko', 11, 0),
    ('GS Lon Lon Ranch Back Wall', 22, 0),
    ('GS Lon Lon Ranch Rain Shed', 22, 0),
    ('GS Lon Lon Ranch House Window', 22, 0),
    ('GS Lon Lon Ranch Tree', 22, 0),
    ('GS Kokiri Bean Patch', 1, 0),
    ('GS Kokiri Know It All House', 1, 0),
    ('GS Kokiri House of Twins', 1, 0),
    ('GS Lost Woods Bean Patch Near Bridge', 13, 0),
    ('GS Lost Woods Bean Patch Near Stage', 13, 0),
    ('GS Lost Woods Above Stage', 13, 0),
    ('GS Sacred Forest Meadow', 10, 0),
    ('GS Outside Ganon's Castle', 20, 0),
    ('GS Hyrule Castle Grotto', 18, 1),
    ('GS Hyrule Castle Tree', 18, 0),
    ('GS Castle Market Guard House', 15, 0),
    ('GS Mountain Crater Bean Patch', 14, 0),
    ('GS Mountain Trail Bean Patch', 3, 0),
    ('GS Mountain Trail Bomb Alcove', 3, 0),
    ('GS Mountain Trail Above Dodongo's Cavern', 3, 0),
    ('GS Mountain Trail Path to Crater', 3, 0),
    ('GS Goron City Center Platform', 4, 0),
    ('GS Goron City Boulder Maze', 4, 0),
    ('GS Death Mountain Crater Crate', 14, 0),
    ('GS Kakariko House Under Construction', 9, 0),
    ('GS Kakariko Skulltula House', 9, 0),
    ('GS Kakariko Guard's House', 9, 0),
    ('GS Kakariko Tree', 9, 0),
    ('GS Kakariko Watchtower', 9, 0),
    ('GS Kakariko Above Impa's House', 9, 0),
    ('GS Graveyard Wall', 2, 0),
    ('GS Graveyard Bean Patch', 2, 0),
    ('GS Zora River Ladder', 12, 0),
    ('GS Zora River Tree', 12, 0),
    ('GS Zora's Fountain Above the Log', 17, 0),
    ('GS Zora River Above Bridge', 12, 0),
    ('GS Zora River Near Raised Grottos', 12, 0),
    ('GS Zora's Fountain Hidden Cave', 17, 1),
    ('GS Zora's Domain Frozen Waterfall', 5, 0),
    ('GS Zora's Fountain Tree', 17, 0),
    ('GS Lake Hylia Bean Patch', 23, 0),
    ('GS Lake Hylia Small Island', 23, 0),
    ('GS Lake Hylia Lab Wall', 23, 0),
    ('GS Lab Underwater Crate', 23, 0),
    ('GS Lake Hylia Giant Tree', 23, 0),
    ('GS Gerudo Valley Bean Patch', 6, 0),
    ('GS Gerudo Valley Small Bridge', 6, 0),
    ('GS Gerudo Valley Pillar', 6, 0),
    ('GS Gerudo Valley Behind Tent', 6, 0),
    ('GS Gerudo Fortress Archery Range', 7, 0),
    ('GS Gerudo Fortress Top Floor', 7, 0),
    ('GS Desert Colossus Bean Patch', 19, 0),
    ('GS Wasteland Ruins', 8, 1),
    ('GS Desert Colossus Hill', 19, 0),
    ('GS Desert Colossus Tree', 19, 0),
    ('Kokiri Shop Item 1', 1, 0),
    ('Kokiri Shop Item 2', 1, 0),
    ('Kokiri Shop Item 3', 1, 0),
    ('Kokiri Shop Item 4', 1, 0),
    ('Kokiri Shop Item 5', 1, 0),
    ('Kokiri Shop Item 6', 1, 0),
    ('Kokiri Shop Item 7', 1, 0),
    ('Kokiri Shop Item 8', 1, 0),
    ('Kakariko Potion Shop Item 1', 9, 0),
    ('Kakariko Potion Shop Item 2', 9, 0),
    ('Kakariko Potion Shop Item 3', 9, 0),
    ('Kakariko Potion Shop Item 4', 9, 0),
    ('Kakariko Potion Shop Item 5', 9, 0),
    ('Kakariko Potion Shop Item 6', 9, 0),
    ('Kakariko Potion Shop Item 7', 9, 0),
    ('Kakariko Potion Shop Item 8', 9, 0),
    ('Bombchu Shop Item 1', 15, 0),
    ('Bombchu Shop Item 2', 15, 0),
    ('Bombchu Shop Item 3', 15, 0),
    ('Bombchu Shop Item 4', 15, 0),
    ('Bombchu Shop Item 5', 15, 0),
    ('Bombchu Shop Item 6', 15, 0),
    ('Bombchu Shop Item 7', 15, 0),
    ('Bombchu Shop Item 8', 15, 0),
    ('Castle Town Potion Shop Item 1', 15, 0),
    ('Castle Town Potion Shop Item 2', 15, 0),
    ('Castle Town Potion Shop Item 3', 15, 0),
    ('Castle Town Potion Shop Item 4', 15, 0),
    ('Castle Town Potion Shop Item 5', 15, 0),
    ('Castle Town Potion Shop Item 6', 15, 0),
    ('Castle Town Potion Shop Item 7', 15, 0),
    ('Castle Town Potion Shop Item 8', 15, 0),
    ('Castle Town Bazaar Item 1', 15, 0),
    ('Castle Town Bazaar Item 2', 15, 0),
    ('Castle Town Bazaar Item 3', 15, 0),
    ('Castle Town Bazaar Item 4', 15, 0),
    ('Castle Town Bazaar Item 5', 15, 0),
    ('Castle Town Bazaar Item 6', 15, 0),
    ('Castle Town Bazaar Item 7', 15, 0),
    ('Castle Town Bazaar Item 8', 15, 0),
    ('Kakariko Bazaar Item 1', 9, 0),
    ('Kakariko Bazaar Item 2', 9, 0),
    ('Kakariko Bazaar Item 3', 9, 0),
    ('Kakariko Bazaar Item 4', 9, 0),
    ('Kakariko Bazaar Item 5', 9, 0),
    ('Kakariko Bazaar Item 6', 9, 0),
    ('Kakariko Bazaar Item 7', 9, 0),
    ('Kakariko Bazaar Item 8', 9, 0),
    ('Zora Shop Item 1', 5, 0),
    ('Zora Shop Item 2', 5, 0),
    ('Zora Shop Item 3', 5, 0),
    ('Zora Shop Item 4', 5, 0),
    ('Zora Shop Item 5', 5, 0),
    ('Zora Shop Item 6', 5, 0),
    ('Zora Shop Item 7', 5, 0),
    ('Zora Shop Item 8', 5, 0),
    ('Goron Shop Item 1', 4, 0),
    ('Goron Shop Item 2', 4, 0),
    ('Goron Shop Item 3', 4, 0),
    ('Goron Shop Item 4', 4, 0),
    ('Goron Shop Item 5', 4, 0),
    ('Goron Shop Item 6', 4, 0),
    ('Goron Shop Item 7', 4, 0),
    ('Goron Shop Item 8', 4, 0),
    ('DC Deku Scrub Deku Nuts', 25, 0),
    ('DC Deku Scrub Deku Sticks', 25, 0),
    ('DC Deku Scrub Deku Seeds', 25, 0),
    ('DC Deku Scrub Deku Shield', 25, 0),
    ('Jabu Deku Scrub Deku Nuts', 26, 0),
    ('GC Deku Scrub Bombs', 34, 0),
    ('GC Deku Scrub Arrows', 34, 0),
    ('GC Deku Scrub Red Potion', 34, 0),
    ('GC Deku Scrub Green Potion', 34, 0),
    ('DT MQ Deku Scrub Deku Shield', 24, 0),
    ('DC MQ Deku Scrub Deku Sticks', 25, 0),
    ('DC MQ Deku Scrub Deku Seeds', 25, 0),
    ('DC MQ Deku Scrub Deku Shield', 25, 0),
    ('DC MQ Deku Scrub Red Potion', 25, 0),
    ('GC MQ Deku Scrub Deku Nuts', 34, 0),
    ('GC MQ Deku Scrub Bombs', 34, 0),
    ('GC MQ Deku Scrub Arrows', 34, 0),
    ('GC MQ Deku Scrub Red Potion', 34, 0),
    ('GC MQ Deku Scrub Green Potion', 34, 0),
    ('HF Grotto Deku Scrub Piece of Heart', 11, 0),
    ('ZR Grotto Deku Scrub Red Potion', 12, 0),
    ('ZR Grotto Deku Scrub Green Potion', 12, 0),
    ('SFM Grotto Deku Scrub Red Potion', 10, 0),
    ('SFM Grotto Deku Scrub Green Potion', 10, 0),
    ('LH Grotto Deku Scrub Deku Nuts', 23, 0),
    ('LH Grotto Deku Scrub Bombs', 23, 0),
    ('LH Grotto Deku Scrub Arrows', 23, 0),
    ('Valley Grotto Deku Scrub Red Potion', 6, 0),
    ('Valley Grotto Deku Scrub Green Potion', 6, 0),
    ('LW Deku Scrub Deku Nuts', 13, 0),
    ('LW Deku Scrub Deku Sticks', 13, 0),
    ('LW Deku Scrub Deku Stick Upgrade', 13, 0),
    ('LW Grotto Deku Scrub Arrows', 13, 0),
    ('LW Grotto Deku Scrub Deku Nut Upgrade', 13, 0),
    ('Desert Grotto Deku Scrub Red Potion', 19, 0),
    ('Desert Grotto Deku Scrub Green Potion', 19, 0),
    ('DMC Deku Scrub Bombs', 14, 1),
    ('DMC Grotto Deku Scrub Deku Nuts', 14, 0),
    ('DMC Grotto Deku Scrub Bombs', 14, 0),
    ('DMC Grotto Deku Scrub Arrows', 14, 0),
    ('Goron Grotto Deku Scrub Deku Nuts', 4, 0),
    ('Goron Grotto Deku Scrub Bombs', 4, 0),
    ('Goron Grotto Deku Scrub Arrows', 4, 0),
    ('LLR Grotto Deku Scrub Deku Nuts', 22, 0),
    ('LLR Grotto Deku Scrub Bombs', 22, 0),
    ('LLR Grotto Deku Scrub Arrows', 22, 0),
    ('LLR Stables Left Cow', 22, 0),
    ('LLR Stables Right Cow', 22, 0),
    ('LLR Tower Right Cow', 22, 0),
    ('LLR Tower Left Cow', 22, 0),
    ('Links House Cow', 35, 1),
    ('Impas House Cow', 9, 0),
    ('Gerudo Valley Cow', 6, 0),
    ('DMT Grotto Cow', 3, 0),
    ('HF Grotto Cow', 11, 0)
;
